### ISSUE TITLE
Preserve latest

### ISSUE THREAD

**Issue by dlemstra** [shanselman/RemoveDotNetCoreSDKInstallers#2]
Maybe this script could be tweaked to keep the latest version installed? So you can run it after a VS update and only preserve the latest SDK?

**Comment by bugproof** [comment]
Would be much better

**Comment by ChristopherGLewis** [comment]
same thoughts - a little more elegant solution here:   https://github.com/ChristopherGLewis/RemoveDotNetCoreSDKInstallers/blob/master/RemoveCoreSDKs.ps1

**Comment by jespersh** [comment]
@ChristopherGLewis Are you sure yours works? I mean it did remove the sdks from `C:\Program Files\dotnet\sdk`, but the programs are still listed as installed in `Add/Remove Programs` and I was able to Uninstall once more

**Comment by ChristopherGLewis** [comment]
> @ChristopherGLewis Are you sure yours works? I mean it did remove the sdks from `C:\Program Files\dotnet\sdk`, but the programs are still listed as installed in `Add/Remove Programs` and I was able to Uninstall once more

Hmm - so some how these are also being installed into the WOW6432Node - I've added search for each removed item in that node also.

**Comment by driesgroblerw** [comment]
Agreed, This is the error: 

```*** Removing  Microsoft ASP.NET Core 2.2.0 Shared Framework (x64) version 2.2.0.0 Uninstall: MsiExec.exe /X{C57A178F-F1CF-3FE0-91BA-27A1EB2C5492}
You cannot call a method on a null-valued expression.
At C:\tools\Software\Remove-DotNetCoreProducts.ps1:74 char:43
+ ... umber = "{$($WOWProduct.UninstallString.split("{")[1].split("}")[0])} ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull```
